### PR TITLE
Add @vzn/reactivity

### PR DESCRIPTION
**Pull request by Exelord**
Hi there! I really like the idea for benchmarking the libraries!

I submitting a benchmark for https://github.com/vznjs/reactivity which is also a fine-grained reactivity lib inspired highly by Solid.

A few notices:
- `dist` and `benchmark` should be build on GH Action to unify the infrastructure the benchmark is running on. So I make them gitignored
- I think there might be something wrong with the implementation of the runner. Solid's `createSignal` and VZN `createValue` has the same implementation however their results diverge drastically. After around ~20 rounds I was able to get the same results but most of the time they vary. Wondering what could be a cause of that 🤔

### CODE REVIEW

**Comment by lxsmnsyc** [comment]
Thanks for the contribution

> dist and benchmark should be build on GH Action to unify the infrastructure the benchmark is running on. So I make them gitignored

I missed the `dist`,  however I intended `benchmark` to be committed. I was thinking of maybe generating a combined output based on the json files, probably something that updates the README for the actual table data.

>  I think there might be something wrong with the implementation of the runner. Solid's createSignal and VZN createValue has the same implementation however their results diverge drastically. After around ~20 rounds I was able to get the same results but most of the time they vary. Wondering what could be a cause of that 🤔

It was actually interesting, specially in JS Framework Benchmarks where Compostate and Solid are actually pretty close in terms of performance. I made sure the bundle includes the browser build, there were no mistakes here. It's probably just Node acting weird.

**Comment by Exelord** [comment]
The thing is, the benchmark will differ depending on what machine it is running, node version, dependencies, etc. which will lead to inconclusive results. Setting up a GH action that outputs the log could be a fair solution to that issue.

I noticed that it has to do something with bundling. When I comment out some of the benchmarks I get different results than where all are enabled

P.S
There is a cool GH action feature that could be used for visualisation: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Comment by lxsmnsyc** [comment]
You're right, I will take a look at the link.

Also, Fabio (author of Oby) also suggested to separate the benchmark runs, just to give time for Node to run the GC. 

Another thing to note is maybe to look for another benchmarking tool. Benny runs on Benchmark.js, the only decent benchmarking tool that I am aware.

**Comment by lxsmnsyc** [comment]
I'm merging this now. I'll just apply the changes later on when I've decided the best course of action.

**Pull request merged**
